version: '3'

services:
  rt:
    build:
        context: .
        args:
            BASE_IMG: $BASE_IMG
    image: $REG/rt/$SRV:$RT
    labels:
      traefik.enable: "true"
      traefik.http.routers.minio-0.rule: PathPrefix(`/minio/`)
    env_file: 
        - .secrets
    volumes:
      - $DATA_DIR:/data
    ports:
      - 9999:9000
    restart: always

networks:
  default:
    external:
      name: rt_default
